ERROR    ligen:test_recharge.py:61 recharge：不输入金额【失败】*****
ERROR    ligen:test_recharge.py:62 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 58, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1