2021-12-04 13:52:53,386 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为空【失败】*****
2021-12-04 13:52:53,386 - [test_withdraw.py-->line:68] - ERROR: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^

