2021-12-04 13:22:00,987 - [test_add.py-->line:54] - INFO: add：加标成功【通过】
2021-12-04 13:22:01,081 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id为空【通过】
2021-12-04 13:22:01,166 - [test_add.py-->line:54] - INFO: add：加标失败—标题为空【通过】
2021-12-04 13:22:01,251 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为空【通过】
2021-12-04 13:22:01,337 - [test_add.py-->line:54] - INFO: add：加标失败—年利率为空【通过】
2021-12-04 13:22:01,423 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限为空【通过】
2021-12-04 13:22:01,511 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限类型为空【通过】
2021-12-04 13:22:01,601 - [test_add.py-->line:54] - INFO: add：加标失败—竞标天数为空【通过】
2021-12-04 13:22:01,695 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id不是当前登录用户【通过】
2021-12-04 13:22:01,787 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为负数【通过】
2021-12-04 13:22:01,874 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为小数【通过】
2021-12-04 13:22:02,441 - [test_audit.py-->line:56] - INFO: audit：审核通过【通过】
2021-12-04 13:22:02,706 - [test_audit.py-->line:56] - INFO: audit：项目不待审核状态【通过】
2021-12-04 13:22:03,161 - [test_audit.py-->line:56] - INFO: audit：审核不通过【通过】
2021-12-04 13:22:03,432 - [test_audit.py-->line:56] - INFO: audit：参数approved_or_not为空【通过】
2021-12-04 13:22:03,702 - [test_audit.py-->line:56] - INFO: audit：项目id为空【通过】
2021-12-04 13:22:03,972 - [test_audit.py-->line:56] - INFO: audit：项目id不存在【通过】
2021-12-04 13:22:04,563 - [test_invest.py-->line:47] - INFO: invest：投资人正常投资【通过】
2021-12-04 13:22:04,658 - [test_invest.py-->line:43] - ERROR: invest：投资人正常投资【失败】*****
2021-12-04 13:22:04,658 - [test_invest.py-->line:44] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_invest.py", line 40, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-12-04 13:22:04,765 - [test_invest.py-->line:47] - INFO: invest：投资人id为空【通过】
2021-12-04 13:22:04,856 - [test_invest.py-->line:47] - INFO: invest：标id为空【通过】
2021-12-04 13:22:04,946 - [test_invest.py-->line:47] - INFO: invest：投资金额为空【通过】
2021-12-04 13:22:05,073 - [test_login.py-->line:35] - INFO: 登录成功【通过】
2021-12-04 13:22:05,162 - [test_login.py-->line:35] - INFO: 手机号为空【通过】
2021-12-04 13:22:05,252 - [test_login.py-->line:35] - INFO: 密码为空【通过】
2021-12-04 13:22:05,378 - [test_login.py-->line:35] - INFO: 手机号未注册【通过】
2021-12-04 13:22:05,508 - [test_login.py-->line:35] - INFO: 密码错误【通过】
2021-12-04 13:22:05,593 - [test_login.py-->line:35] - INFO: 手机号格式错误【通过】
2021-12-04 13:22:06,206 - [test_recharge.py-->line:65] - INFO: recharge：充值成功【通过】
2021-12-04 13:22:06,819 - [test_recharge.py-->line:65] - INFO: recharge：充值成功-金额为小数【通过】
2021-12-04 13:22:07,042 - [test_recharge.py-->line:65] - INFO: recharge：id错误(不是当前用的id)【通过】
2021-12-04 13:22:07,225 - [test_recharge.py-->line:65] - INFO: recharge：不输入id【通过】
2021-12-04 13:22:07,393 - [test_recharge.py-->line:61] - ERROR: recharge：不输入金额【失败】*****
2021-12-04 13:22:07,393 - [test_recharge.py-->line:62] - ERROR: 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 58, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1
2021-12-04 13:22:07,573 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为负数【失败】*****
2021-12-04 13:22:07,573 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:22:07,745 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为500001【失败】*****
2021-12-04 13:22:07,746 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:22:07,921 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额非数字【失败】*****
2021-12-04 13:22:07,921 - [test_recharge.py-->line:62] - ERROR: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型

2021-12-04 13:22:08,095 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额小数点3位【失败】*****
2021-12-04 13:22:08,095 - [test_recharge.py-->line:62] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:22:08,478 - [test_register.py-->line:44] - INFO: 注册：注册成功-带注册名通过！
2021-12-04 13:22:08,871 - [test_register.py-->line:44] - INFO: 注册：成功-不带用户名通过！
2021-12-04 13:22:08,964 - [test_register.py-->line:44] - INFO: 注册：不输入手机号通过！
2021-12-04 13:22:09,052 - [test_register.py-->line:44] - INFO: 注册：手机号长度10位通过！
2021-12-04 13:22:09,140 - [test_register.py-->line:44] - INFO: 注册：手机号长度12位通过！
2021-12-04 13:22:09,226 - [test_register.py-->line:44] - INFO: 注册：手机号含有非法字符通过！
2021-12-04 13:22:09,355 - [test_register.py-->line:44] - INFO: 注册：已注册过的手机号通过！
2021-12-04 13:22:09,566 - [test_register.py-->line:44] - INFO: 注册：密码7位通过！
2021-12-04 13:22:09,781 - [test_register.py-->line:44] - INFO: 注册：密码17位通过！
2021-12-04 13:22:09,992 - [test_register.py-->line:44] - INFO: 注册：不输入密码通过！
2021-12-04 13:22:10,261 - [test_register.py-->line:40] - ERROR: 注册：注册名11位失败！
2021-12-04 13:22:10,261 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:22:10,480 - [test_register.py-->line:44] - INFO: 注册：类型输入非0，1内容通过！
2021-12-04 13:22:10,745 - [test_register.py-->line:40] - ERROR: 注册：手机号为字符串类型失败！
2021-12-04 13:22:10,746 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:22:11,684 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-整数【通过】
2021-12-04 13:22:12,294 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-1位小数【通过】
2021-12-04 13:22:12,907 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-2位小数【通过】
2021-12-04 13:22:13,513 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-50万【通过】
2021-12-04 13:22:13,730 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为空【通过】
2021-12-04 13:22:13,910 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id不存在【通过】
2021-12-04 13:22:14,095 - [test_withdraw.py-->line:67] - ERROR: withdraw：会员id为数值【失败】*****
2021-12-04 13:22:14,095 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:22:14,329 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为小数【通过】
2021-12-04 13:22:14,511 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为0【失败】*****
2021-12-04 13:22:14,511 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:22:14,686 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为负数【失败】*****
2021-12-04 13:22:14,687 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:22:14,867 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为空【失败】*****
2021-12-04 13:22:14,867 - [test_withdraw.py-->line:68] - ERROR: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^

2021-12-04 13:22:15,074 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-3位小数【失败】*****
2021-12-04 13:22:15,075 - [test_withdraw.py-->line:68] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:22:15,254 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-大于50万【失败】*****
2021-12-04 13:22:15,255 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:22:15,430 - [test_withdraw.py-->line:71] - INFO: withdraw：提现金额-非数字【通过】
2021-12-04 13:43:14,680 - [test_add.py-->line:54] - INFO: add：加标成功【通过】
2021-12-04 13:43:14,785 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id为空【通过】
2021-12-04 13:43:14,886 - [test_add.py-->line:54] - INFO: add：加标失败—标题为空【通过】
2021-12-04 13:43:14,980 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为空【通过】
2021-12-04 13:43:15,077 - [test_add.py-->line:54] - INFO: add：加标失败—年利率为空【通过】
2021-12-04 13:43:15,173 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限为空【通过】
2021-12-04 13:43:15,266 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限类型为空【通过】
2021-12-04 13:43:15,356 - [test_add.py-->line:54] - INFO: add：加标失败—竞标天数为空【通过】
2021-12-04 13:43:15,454 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id不是当前登录用户【通过】
2021-12-04 13:43:15,551 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为负数【通过】
2021-12-04 13:43:15,649 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为小数【通过】
2021-12-04 13:43:16,221 - [test_audit.py-->line:56] - INFO: audit：审核通过【通过】
2021-12-04 13:43:16,498 - [test_audit.py-->line:56] - INFO: audit：项目不待审核状态【通过】
2021-12-04 13:43:16,951 - [test_audit.py-->line:56] - INFO: audit：审核不通过【通过】
2021-12-04 13:43:17,235 - [test_audit.py-->line:56] - INFO: audit：参数approved_or_not为空【通过】
2021-12-04 13:43:17,507 - [test_audit.py-->line:56] - INFO: audit：项目id为空【通过】
2021-12-04 13:43:17,788 - [test_audit.py-->line:56] - INFO: audit：项目id不存在【通过】
2021-12-04 13:43:18,407 - [test_invest.py-->line:47] - INFO: invest：投资人正常投资【通过】
2021-12-04 13:43:18,510 - [test_invest.py-->line:43] - ERROR: invest：投资人正常投资【失败】*****
2021-12-04 13:43:18,510 - [test_invest.py-->line:44] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_invest.py", line 40, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-12-04 13:43:18,934 - [test_invest.py-->line:47] - INFO: invest：投资人id为空【通过】
2021-12-04 13:43:19,035 - [test_invest.py-->line:47] - INFO: invest：标id为空【通过】
2021-12-04 13:43:19,126 - [test_invest.py-->line:47] - INFO: invest：投资金额为空【通过】
2021-12-04 13:43:19,260 - [test_login.py-->line:35] - INFO: 登录成功【通过】
2021-12-04 13:43:19,359 - [test_login.py-->line:35] - INFO: 手机号为空【通过】
2021-12-04 13:43:19,448 - [test_login.py-->line:35] - INFO: 密码为空【通过】
2021-12-04 13:43:19,578 - [test_login.py-->line:35] - INFO: 手机号未注册【通过】
2021-12-04 13:43:19,714 - [test_login.py-->line:35] - INFO: 密码错误【通过】
2021-12-04 13:43:19,802 - [test_login.py-->line:35] - INFO: 手机号格式错误【通过】
2021-12-04 13:43:20,407 - [test_recharge.py-->line:65] - INFO: recharge：充值成功【通过】
2021-12-04 13:43:21,028 - [test_recharge.py-->line:65] - INFO: recharge：充值成功-金额为小数【通过】
2021-12-04 13:43:21,268 - [test_recharge.py-->line:65] - INFO: recharge：id错误(不是当前用的id)【通过】
2021-12-04 13:43:21,701 - [test_recharge.py-->line:65] - INFO: recharge：不输入id【通过】
2021-12-04 13:43:21,888 - [test_recharge.py-->line:61] - ERROR: recharge：不输入金额【失败】*****
2021-12-04 13:43:21,889 - [test_recharge.py-->line:62] - ERROR: 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 58, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1
2021-12-04 13:43:22,085 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为负数【失败】*****
2021-12-04 13:43:22,085 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:43:22,280 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为500001【失败】*****
2021-12-04 13:43:22,280 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:43:22,471 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额非数字【失败】*****
2021-12-04 13:43:22,471 - [test_recharge.py-->line:62] - ERROR: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型

2021-12-04 13:43:22,663 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额小数点3位【失败】*****
2021-12-04 13:43:22,663 - [test_recharge.py-->line:62] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:43:23,070 - [test_register.py-->line:44] - INFO: 注册：注册成功-带注册名通过！
2021-12-04 13:43:23,460 - [test_register.py-->line:44] - INFO: 注册：成功-不带用户名通过！
2021-12-04 13:43:23,556 - [test_register.py-->line:44] - INFO: 注册：不输入手机号通过！
2021-12-04 13:43:23,652 - [test_register.py-->line:44] - INFO: 注册：手机号长度10位通过！
2021-12-04 13:43:23,746 - [test_register.py-->line:44] - INFO: 注册：手机号长度12位通过！
2021-12-04 13:43:23,840 - [test_register.py-->line:44] - INFO: 注册：手机号含有非法字符通过！
2021-12-04 13:43:23,974 - [test_register.py-->line:44] - INFO: 注册：已注册过的手机号通过！
2021-12-04 13:43:24,196 - [test_register.py-->line:44] - INFO: 注册：密码7位通过！
2021-12-04 13:43:24,418 - [test_register.py-->line:44] - INFO: 注册：密码17位通过！
2021-12-04 13:43:24,642 - [test_register.py-->line:44] - INFO: 注册：不输入密码通过！
2021-12-04 13:43:24,912 - [test_register.py-->line:40] - ERROR: 注册：注册名11位失败！
2021-12-04 13:43:24,913 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:43:25,152 - [test_register.py-->line:44] - INFO: 注册：类型输入非0，1内容通过！
2021-12-04 13:43:25,430 - [test_register.py-->line:40] - ERROR: 注册：手机号为字符串类型失败！
2021-12-04 13:43:25,431 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:43:26,616 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-整数【通过】
2021-12-04 13:43:27,237 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-1位小数【通过】
2021-12-04 13:43:27,851 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-2位小数【通过】
2021-12-04 13:43:28,454 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-50万【通过】
2021-12-04 13:43:28,679 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为空【通过】
2021-12-04 13:43:28,862 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id不存在【通过】
2021-12-04 13:43:29,063 - [test_withdraw.py-->line:67] - ERROR: withdraw：会员id为数值【失败】*****
2021-12-04 13:43:29,064 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:43:29,317 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为小数【通过】
2021-12-04 13:43:29,513 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为0【失败】*****
2021-12-04 13:43:29,513 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:43:29,727 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为负数【失败】*****
2021-12-04 13:43:29,728 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:43:29,919 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为空【失败】*****
2021-12-04 13:43:29,920 - [test_withdraw.py-->line:68] - ERROR: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^

2021-12-04 13:43:30,115 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-3位小数【失败】*****
2021-12-04 13:43:30,115 - [test_withdraw.py-->line:68] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:43:30,318 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-大于50万【失败】*****
2021-12-04 13:43:30,319 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:43:30,522 - [test_withdraw.py-->line:71] - INFO: withdraw：提现金额-非数字【通过】
2021-12-04 13:46:01,893 - [test_add.py-->line:54] - INFO: add：加标成功【通过】
2021-12-04 13:46:01,989 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id为空【通过】
2021-12-04 13:46:02,085 - [test_add.py-->line:54] - INFO: add：加标失败—标题为空【通过】
2021-12-04 13:46:02,181 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为空【通过】
2021-12-04 13:46:02,273 - [test_add.py-->line:54] - INFO: add：加标失败—年利率为空【通过】
2021-12-04 13:46:02,366 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限为空【通过】
2021-12-04 13:46:02,455 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限类型为空【通过】
2021-12-04 13:46:02,551 - [test_add.py-->line:54] - INFO: add：加标失败—竞标天数为空【通过】
2021-12-04 13:46:02,647 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id不是当前登录用户【通过】
2021-12-04 13:46:02,745 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为负数【通过】
2021-12-04 13:46:02,839 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为小数【通过】
2021-12-04 13:46:03,409 - [test_audit.py-->line:56] - INFO: audit：审核通过【通过】
2021-12-04 13:46:03,682 - [test_audit.py-->line:56] - INFO: audit：项目不待审核状态【通过】
2021-12-04 13:46:04,141 - [test_audit.py-->line:56] - INFO: audit：审核不通过【通过】
2021-12-04 13:46:04,427 - [test_audit.py-->line:56] - INFO: audit：参数approved_or_not为空【通过】
2021-12-04 13:46:04,702 - [test_audit.py-->line:56] - INFO: audit：项目id为空【通过】
2021-12-04 13:46:04,992 - [test_audit.py-->line:56] - INFO: audit：项目id不存在【通过】
2021-12-04 13:46:05,617 - [test_invest.py-->line:47] - INFO: invest：投资人正常投资【通过】
2021-12-04 13:46:05,725 - [test_invest.py-->line:43] - ERROR: invest：投资人正常投资【失败】*****
2021-12-04 13:46:05,725 - [test_invest.py-->line:44] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_invest.py", line 40, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-12-04 13:46:06,112 - [test_invest.py-->line:47] - INFO: invest：投资人id为空【通过】
2021-12-04 13:46:06,204 - [test_invest.py-->line:47] - INFO: invest：标id为空【通过】
2021-12-04 13:46:06,296 - [test_invest.py-->line:47] - INFO: invest：投资金额为空【通过】
2021-12-04 13:46:06,429 - [test_login.py-->line:35] - INFO: 登录成功【通过】
2021-12-04 13:46:06,524 - [test_login.py-->line:35] - INFO: 手机号为空【通过】
2021-12-04 13:46:06,621 - [test_login.py-->line:35] - INFO: 密码为空【通过】
2021-12-04 13:46:06,758 - [test_login.py-->line:35] - INFO: 手机号未注册【通过】
2021-12-04 13:46:06,897 - [test_login.py-->line:35] - INFO: 密码错误【通过】
2021-12-04 13:46:07,002 - [test_login.py-->line:35] - INFO: 手机号格式错误【通过】
2021-12-04 13:46:07,626 - [test_recharge.py-->line:65] - INFO: recharge：充值成功【通过】
2021-12-04 13:46:08,235 - [test_recharge.py-->line:65] - INFO: recharge：充值成功-金额为小数【通过】
2021-12-04 13:46:08,457 - [test_recharge.py-->line:65] - INFO: recharge：id错误(不是当前用的id)【通过】
2021-12-04 13:46:08,640 - [test_recharge.py-->line:65] - INFO: recharge：不输入id【通过】
2021-12-04 13:46:08,828 - [test_recharge.py-->line:61] - ERROR: recharge：不输入金额【失败】*****
2021-12-04 13:46:08,828 - [test_recharge.py-->line:62] - ERROR: 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 58, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1
2021-12-04 13:46:09,024 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为负数【失败】*****
2021-12-04 13:46:09,024 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:46:09,210 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为500001【失败】*****
2021-12-04 13:46:09,210 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:46:09,407 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额非数字【失败】*****
2021-12-04 13:46:09,408 - [test_recharge.py-->line:62] - ERROR: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型

2021-12-04 13:46:09,599 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额小数点3位【失败】*****
2021-12-04 13:46:09,599 - [test_recharge.py-->line:62] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:46:10,004 - [test_register.py-->line:44] - INFO: 注册：注册成功-带注册名通过！
2021-12-04 13:46:10,407 - [test_register.py-->line:44] - INFO: 注册：成功-不带用户名通过！
2021-12-04 13:46:10,503 - [test_register.py-->line:44] - INFO: 注册：不输入手机号通过！
2021-12-04 13:46:10,599 - [test_register.py-->line:44] - INFO: 注册：手机号长度10位通过！
2021-12-04 13:46:10,693 - [test_register.py-->line:44] - INFO: 注册：手机号长度12位通过！
2021-12-04 13:46:10,785 - [test_register.py-->line:44] - INFO: 注册：手机号含有非法字符通过！
2021-12-04 13:46:10,923 - [test_register.py-->line:44] - INFO: 注册：已注册过的手机号通过！
2021-12-04 13:46:11,139 - [test_register.py-->line:44] - INFO: 注册：密码7位通过！
2021-12-04 13:46:11,360 - [test_register.py-->line:44] - INFO: 注册：密码17位通过！
2021-12-04 13:46:11,591 - [test_register.py-->line:44] - INFO: 注册：不输入密码通过！
2021-12-04 13:46:11,858 - [test_register.py-->line:40] - ERROR: 注册：注册名11位失败！
2021-12-04 13:46:11,858 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:46:12,087 - [test_register.py-->line:44] - INFO: 注册：类型输入非0，1内容通过！
2021-12-04 13:46:12,355 - [test_register.py-->line:40] - ERROR: 注册：手机号为字符串类型失败！
2021-12-04 13:46:12,355 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:46:13,297 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-整数【通过】
2021-12-04 13:46:13,911 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-1位小数【通过】
2021-12-04 13:46:14,518 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-2位小数【通过】
2021-12-04 13:46:15,114 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-50万【通过】
2021-12-04 13:46:15,336 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为空【通过】
2021-12-04 13:46:15,521 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id不存在【通过】
2021-12-04 13:46:15,708 - [test_withdraw.py-->line:67] - ERROR: withdraw：会员id为数值【失败】*****
2021-12-04 13:46:15,708 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:46:15,956 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为小数【通过】
2021-12-04 13:46:16,148 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为0【失败】*****
2021-12-04 13:46:16,148 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:46:16,350 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为负数【失败】*****
2021-12-04 13:46:16,350 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:46:16,546 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为空【失败】*****
2021-12-04 13:46:16,546 - [test_withdraw.py-->line:68] - ERROR: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^

2021-12-04 13:46:16,732 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-3位小数【失败】*****
2021-12-04 13:46:16,733 - [test_withdraw.py-->line:68] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:46:16,927 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-大于50万【失败】*****
2021-12-04 13:46:16,927 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:46:17,118 - [test_withdraw.py-->line:71] - INFO: withdraw：提现金额-非数字【通过】
2021-12-04 13:52:38,609 - [test_add.py-->line:54] - INFO: add：加标成功【通过】
2021-12-04 13:52:38,707 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id为空【通过】
2021-12-04 13:52:38,798 - [test_add.py-->line:54] - INFO: add：加标失败—标题为空【通过】
2021-12-04 13:52:38,888 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为空【通过】
2021-12-04 13:52:38,983 - [test_add.py-->line:54] - INFO: add：加标失败—年利率为空【通过】
2021-12-04 13:52:39,074 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限为空【通过】
2021-12-04 13:52:39,165 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限类型为空【通过】
2021-12-04 13:52:39,262 - [test_add.py-->line:54] - INFO: add：加标失败—竞标天数为空【通过】
2021-12-04 13:52:39,358 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id不是当前登录用户【通过】
2021-12-04 13:52:39,451 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为负数【通过】
2021-12-04 13:52:39,547 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为小数【通过】
2021-12-04 13:52:40,128 - [test_audit.py-->line:56] - INFO: audit：审核通过【通过】
2021-12-04 13:52:40,427 - [test_audit.py-->line:56] - INFO: audit：项目不待审核状态【通过】
2021-12-04 13:52:40,879 - [test_audit.py-->line:56] - INFO: audit：审核不通过【通过】
2021-12-04 13:52:41,148 - [test_audit.py-->line:56] - INFO: audit：参数approved_or_not为空【通过】
2021-12-04 13:52:41,427 - [test_audit.py-->line:56] - INFO: audit：项目id为空【通过】
2021-12-04 13:52:41,715 - [test_audit.py-->line:56] - INFO: audit：项目id不存在【通过】
2021-12-04 13:52:42,317 - [test_invest.py-->line:47] - INFO: invest：投资人正常投资【通过】
2021-12-04 13:52:42,423 - [test_invest.py-->line:43] - ERROR: invest：投资人正常投资【失败】*****
2021-12-04 13:52:42,424 - [test_invest.py-->line:44] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_invest.py", line 40, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-12-04 13:52:42,843 - [test_invest.py-->line:47] - INFO: invest：投资人id为空【通过】
2021-12-04 13:52:42,940 - [test_invest.py-->line:47] - INFO: invest：标id为空【通过】
2021-12-04 13:52:43,035 - [test_invest.py-->line:47] - INFO: invest：投资金额为空【通过】
2021-12-04 13:52:43,169 - [test_login.py-->line:35] - INFO: 登录成功【通过】
2021-12-04 13:52:43,265 - [test_login.py-->line:35] - INFO: 手机号为空【通过】
2021-12-04 13:52:43,359 - [test_login.py-->line:35] - INFO: 密码为空【通过】
2021-12-04 13:52:43,499 - [test_login.py-->line:35] - INFO: 手机号未注册【通过】
2021-12-04 13:52:43,632 - [test_login.py-->line:35] - INFO: 密码错误【通过】
2021-12-04 13:52:43,727 - [test_login.py-->line:35] - INFO: 手机号格式错误【通过】
2021-12-04 13:52:44,329 - [test_recharge.py-->line:65] - INFO: recharge：充值成功【通过】
2021-12-04 13:52:44,953 - [test_recharge.py-->line:65] - INFO: recharge：充值成功-金额为小数【通过】
2021-12-04 13:52:45,179 - [test_recharge.py-->line:65] - INFO: recharge：id错误(不是当前用的id)【通过】
2021-12-04 13:52:45,363 - [test_recharge.py-->line:65] - INFO: recharge：不输入id【通过】
2021-12-04 13:52:45,549 - [test_recharge.py-->line:61] - ERROR: recharge：不输入金额【失败】*****
2021-12-04 13:52:45,549 - [test_recharge.py-->line:62] - ERROR: 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 58, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1
2021-12-04 13:52:45,742 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为负数【失败】*****
2021-12-04 13:52:45,742 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:52:45,933 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为500001【失败】*****
2021-12-04 13:52:45,933 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:52:46,126 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额非数字【失败】*****
2021-12-04 13:52:46,126 - [test_recharge.py-->line:62] - ERROR: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型

2021-12-04 13:52:46,315 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额小数点3位【失败】*****
2021-12-04 13:52:46,315 - [test_recharge.py-->line:62] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:52:46,725 - [test_register.py-->line:44] - INFO: 注册：注册成功-带注册名通过！
2021-12-04 13:52:47,115 - [test_register.py-->line:44] - INFO: 注册：成功-不带用户名通过！
2021-12-04 13:52:47,207 - [test_register.py-->line:44] - INFO: 注册：不输入手机号通过！
2021-12-04 13:52:47,298 - [test_register.py-->line:44] - INFO: 注册：手机号长度10位通过！
2021-12-04 13:52:47,389 - [test_register.py-->line:44] - INFO: 注册：手机号长度12位通过！
2021-12-04 13:52:47,481 - [test_register.py-->line:44] - INFO: 注册：手机号含有非法字符通过！
2021-12-04 13:52:47,622 - [test_register.py-->line:44] - INFO: 注册：已注册过的手机号通过！
2021-12-04 13:52:47,838 - [test_register.py-->line:44] - INFO: 注册：密码7位通过！
2021-12-04 13:52:48,054 - [test_register.py-->line:44] - INFO: 注册：密码17位通过！
2021-12-04 13:52:48,271 - [test_register.py-->line:44] - INFO: 注册：不输入密码通过！
2021-12-04 13:52:48,534 - [test_register.py-->line:40] - ERROR: 注册：注册名11位失败！
2021-12-04 13:52:48,534 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:52:48,770 - [test_register.py-->line:44] - INFO: 注册：类型输入非0，1内容通过！
2021-12-04 13:52:49,046 - [test_register.py-->line:40] - ERROR: 注册：手机号为字符串类型失败！
2021-12-04 13:52:49,047 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:52:50,129 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-整数【通过】
2021-12-04 13:52:50,741 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-1位小数【通过】
2021-12-04 13:52:51,349 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-2位小数【通过】
2021-12-04 13:52:51,956 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-50万【通过】
2021-12-04 13:52:52,200 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为空【通过】
2021-12-04 13:52:52,379 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id不存在【通过】
2021-12-04 13:52:52,569 - [test_withdraw.py-->line:67] - ERROR: withdraw：会员id为数值【失败】*****
2021-12-04 13:52:52,570 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:52:52,807 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为小数【通过】
2021-12-04 13:52:53,004 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为0【失败】*****
2021-12-04 13:52:53,004 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:52:53,195 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为负数【失败】*****
2021-12-04 13:52:53,195 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:52:53,386 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为空【失败】*****
2021-12-04 13:52:53,386 - [test_withdraw.py-->line:68] - ERROR: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^

2021-12-04 13:52:53,570 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-3位小数【失败】*****
2021-12-04 13:52:53,570 - [test_withdraw.py-->line:68] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:52:53,763 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-大于50万【失败】*****
2021-12-04 13:52:53,764 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:52:53,965 - [test_withdraw.py-->line:71] - INFO: withdraw：提现金额-非数字【通过】
2021-12-04 13:53:37,932 - [test_add.py-->line:54] - INFO: add：加标成功【通过】
2021-12-04 13:53:38,029 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id为空【通过】
2021-12-04 13:53:38,119 - [test_add.py-->line:54] - INFO: add：加标失败—标题为空【通过】
2021-12-04 13:53:38,216 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为空【通过】
2021-12-04 13:53:38,309 - [test_add.py-->line:54] - INFO: add：加标失败—年利率为空【通过】
2021-12-04 13:53:38,401 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限为空【通过】
2021-12-04 13:53:38,492 - [test_add.py-->line:54] - INFO: add：加标失败—借款期限类型为空【通过】
2021-12-04 13:53:38,582 - [test_add.py-->line:54] - INFO: add：加标失败—竞标天数为空【通过】
2021-12-04 13:53:38,677 - [test_add.py-->line:54] - INFO: add：加标失败—借款人id不是当前登录用户【通过】
2021-12-04 13:53:38,777 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为负数【通过】
2021-12-04 13:53:38,872 - [test_add.py-->line:54] - INFO: add：加标失败—借款金额为小数【通过】
2021-12-04 13:53:39,459 - [test_audit.py-->line:56] - INFO: audit：审核通过【通过】
2021-12-04 13:53:40,003 - [test_audit.py-->line:56] - INFO: audit：项目不待审核状态【通过】
2021-12-04 13:53:40,453 - [test_audit.py-->line:56] - INFO: audit：审核不通过【通过】
2021-12-04 13:53:40,736 - [test_audit.py-->line:56] - INFO: audit：参数approved_or_not为空【通过】
2021-12-04 13:53:41,027 - [test_audit.py-->line:56] - INFO: audit：项目id为空【通过】
2021-12-04 13:53:41,298 - [test_audit.py-->line:56] - INFO: audit：项目id不存在【通过】
2021-12-04 13:53:41,869 - [test_invest.py-->line:47] - INFO: invest：投资人正常投资【通过】
2021-12-04 13:53:42,737 - [test_invest.py-->line:43] - ERROR: invest：投资人正常投资【失败】*****
2021-12-04 13:53:42,737 - [test_invest.py-->line:44] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_invest.py", line 40, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-12-04 13:53:43,130 - [test_invest.py-->line:47] - INFO: invest：投资人id为空【通过】
2021-12-04 13:53:43,220 - [test_invest.py-->line:47] - INFO: invest：标id为空【通过】
2021-12-04 13:53:43,318 - [test_invest.py-->line:47] - INFO: invest：投资金额为空【通过】
2021-12-04 13:53:43,455 - [test_login.py-->line:35] - INFO: 登录成功【通过】
2021-12-04 13:53:43,549 - [test_login.py-->line:35] - INFO: 手机号为空【通过】
2021-12-04 13:53:43,641 - [test_login.py-->line:35] - INFO: 密码为空【通过】
2021-12-04 13:53:43,779 - [test_login.py-->line:35] - INFO: 手机号未注册【通过】
2021-12-04 13:53:43,908 - [test_login.py-->line:35] - INFO: 密码错误【通过】
2021-12-04 13:53:43,999 - [test_login.py-->line:35] - INFO: 手机号格式错误【通过】
2021-12-04 13:53:44,611 - [test_recharge.py-->line:65] - INFO: recharge：充值成功【通过】
2021-12-04 13:53:45,300 - [test_recharge.py-->line:65] - INFO: recharge：充值成功-金额为小数【通过】
2021-12-04 13:53:45,529 - [test_recharge.py-->line:65] - INFO: recharge：id错误(不是当前用的id)【通过】
2021-12-04 13:53:45,710 - [test_recharge.py-->line:65] - INFO: recharge：不输入id【通过】
2021-12-04 13:53:45,887 - [test_recharge.py-->line:61] - ERROR: recharge：不输入金额【失败】*****
2021-12-04 13:53:45,887 - [test_recharge.py-->line:62] - ERROR: 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 58, in test_recharge
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1
2021-12-04 13:53:46,073 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为负数【失败】*****
2021-12-04 13:53:46,073 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:53:46,265 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额为500001【失败】*****
2021-12-04 13:53:46,265 - [test_recharge.py-->line:62] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:53:46,454 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额非数字【失败】*****
2021-12-04 13:53:46,454 - [test_recharge.py-->line:62] - ERROR: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '数字格式化异常' != '金额必须为数值型'
- 数字格式化异常
+ 金额必须为数值型

2021-12-04 13:53:46,641 - [test_recharge.py-->line:61] - ERROR: recharge：充值金额小数点3位【失败】*****
2021-12-04 13:53:46,641 - [test_recharge.py-->line:62] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_recharge.py", line 59, in test_recharge
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:53:47,049 - [test_register.py-->line:44] - INFO: 注册：注册成功-带注册名通过！
2021-12-04 13:53:47,445 - [test_register.py-->line:44] - INFO: 注册：成功-不带用户名通过！
2021-12-04 13:53:47,545 - [test_register.py-->line:44] - INFO: 注册：不输入手机号通过！
2021-12-04 13:53:47,640 - [test_register.py-->line:44] - INFO: 注册：手机号长度10位通过！
2021-12-04 13:53:47,735 - [test_register.py-->line:44] - INFO: 注册：手机号长度12位通过！
2021-12-04 13:53:47,831 - [test_register.py-->line:44] - INFO: 注册：手机号含有非法字符通过！
2021-12-04 13:53:47,960 - [test_register.py-->line:44] - INFO: 注册：已注册过的手机号通过！
2021-12-04 13:53:48,180 - [test_register.py-->line:44] - INFO: 注册：密码7位通过！
2021-12-04 13:53:48,398 - [test_register.py-->line:44] - INFO: 注册：密码17位通过！
2021-12-04 13:53:48,623 - [test_register.py-->line:44] - INFO: 注册：不输入密码通过！
2021-12-04 13:53:48,900 - [test_register.py-->line:40] - ERROR: 注册：注册名11位失败！
2021-12-04 13:53:48,900 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:53:49,135 - [test_register.py-->line:44] - INFO: 注册：类型输入非0，1内容通过！
2021-12-04 13:53:49,404 - [test_register.py-->line:40] - ERROR: 注册：手机号为字符串类型失败！
2021-12-04 13:53:49,404 - [test_register.py-->line:41] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_register.py", line 33, in test_register
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:53:50,364 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-整数【通过】
2021-12-04 13:53:50,983 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-1位小数【通过】
2021-12-04 13:53:51,607 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-2位小数【通过】
2021-12-04 13:53:52,220 - [test_withdraw.py-->line:71] - INFO: withdraw：提现成功-50万【通过】
2021-12-04 13:53:52,459 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为空【通过】
2021-12-04 13:53:52,639 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id不存在【通过】
2021-12-04 13:53:52,838 - [test_withdraw.py-->line:67] - ERROR: withdraw：会员id为数值【失败】*****
2021-12-04 13:53:52,838 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:53:53,071 - [test_withdraw.py-->line:71] - INFO: withdraw：会员id为小数【通过】
2021-12-04 13:53:53,265 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为0【失败】*****
2021-12-04 13:53:53,265 - [test_withdraw.py-->line:68] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 64, in test_withdraw
    self.assertEqual(res.json()['code'],expected['code'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-12-04 13:53:53,715 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为负数【失败】*****
2021-12-04 13:53:53,716 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:53:53,899 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额为空【失败】*****
2021-12-04 13:53:53,900 - [test_withdraw.py-->line:68] - ERROR: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额为空' != '金额为空'
- 余额为空
? ^
+ 金额为空
? ^

2021-12-04 13:53:54,093 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-3位小数【失败】*****
2021-12-04 13:53:54,093 - [test_withdraw.py-->line:68] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-12-04 13:53:54,286 - [test_withdraw.py-->line:67] - ERROR: withdraw：提现金额-大于50万【失败】*****
2021-12-04 13:53:54,286 - [test_withdraw.py-->line:68] - ERROR: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\docjer实战接口自动化\LG_jiekou_unittest\testcase\test_withdraw.py", line 65, in test_withdraw
    self.assertEqual(res.json()['msg'], expected['msg'])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于5000000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于5000000
? ^                    -
+ 金额必须大于0并且小于或者等于500000
? ^

2021-12-04 13:53:54,479 - [test_withdraw.py-->line:71] - INFO: withdraw：提现金额-非数字【通过】
